
package fr.eseo.servicesweb.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.0
 * Wed Mar 13 08:20:44 CET 2019
 * Generated source version: 3.3.0
 */

@XmlRootElement(name = "reserverChambre", namespace = "http://servicesweb.eseo.fr/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reserverChambre", namespace = "http://servicesweb.eseo.fr/")

public class ReserverChambre {

    @XmlElement(name = "arg0")
    private fr.eseo.servicesweb.Reservation arg0;

    public fr.eseo.servicesweb.Reservation getArg0() {
        return this.arg0;
    }

    public void setArg0(fr.eseo.servicesweb.Reservation newArg0)  {
        this.arg0 = newArg0;
    }

}

